#!/bin/bash
#
# Obtain the latest ROCm and amdgpu package versions from repo.radeon.com.
# Use QUIET=true to only display the version tag.
# Use ONLY_ONE=[ROCM|AMDGPU] to output one version tag only.

RADEON_REPO=${RADEON_REPO:-https://repo.radeon.com}
QUIET=${QUIET:-false}
ONLY_ONE=${ONLY_ONE:-false}
WSL_INSTALL=${WSL_INSTALL:-false}

ROCM_REMOTE=${RADEON_REPO}/rocm/apt/
AMDGPU_REMOTE=${RADEON_REPO}/amdgpu/
WSL_REMOTE=${RADEON_REPO}/amdgpu/

wsl_version () {
    VERSIONS=$(curl -s "${1}" | \
      sed -nE 's/^<a href="([0-9.]+*)\/">*.*/\1/p' | \
      sort -rg)
    mapfile -t VERSION_ARRAY <<< "${VERSIONS}"
    WSL_SUPPORT="none"
    for VERSION in "${VERSION_ARRAY[@]}"; do
        if curl -s "${1}${VERSION}/ubuntu/pool/main/h/" | grep -qi wsl; then
            WSL_SUPPORT=${VERSION}
            break
        fi
    done
    echo "${WSL_SUPPORT}"
}

parse_repo () {
    VERSION=$(curl -s "${1}" | \
      sed -nE 's/^<a href="([0-9.]+*)\/">*.*/\1/p' | \
      sort -g | tail -n 1)
    echo "${VERSION}"
}

if [ "${ONLY_ONE}" != "AMDGPU" ]; then
    if [ "${WSL_INSTALL}" = "true" ]; then
        ROCM_VERSION=$(wsl_version "${WSL_REMOTE}")
    else
        ROCM_VERSION=$(parse_repo "${ROCM_REMOTE}")
    fi
    if [ "${QUIET}" = "true" ]; then
        echo "${ROCM_VERSION}"
    else
        if [ "${WSL_INSTALL}" = "true" ]; then
            echo "ROCm latest (wsl): ${ROCM_VERSION}."
        else
            echo "ROCm latest: ${ROCM_VERSION}."
        fi
    fi
fi

if [ "${ONLY_ONE}" != "ROCM" ]; then
    if [ "${WSL_INSTALL}" = "true" ]; then
        AMDGPU_VERSION="none"
    else
        AMDGPU_VERSION=$(parse_repo "${AMDGPU_REMOTE}")
    fi
    if [ "${QUIET}" = "true" ]; then
        echo "${AMDGPU_VERSION}"
    else
        if [ "${WSL_INSTALL}" = "true" ]; then
            echo "AMDGPU latest (wsl): ${AMDGPU_VERSION}."
        else
            echo "AMDGPU latest: ${AMDGPU_VERSION}."
        fi
    fi
fi
